/**
 * Movies
 */
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_STATUS = 'LOAD_MOVIES_STATUS';
/**
 * Slider
 */
export const SET_SLIDER_THEME = 'SET_SLIDER_THEME';
export const SET_RETURN_PATH = 'SET_RETURN_PATH';
/**
 * News
 */
export const SET_NEWS_SCROLL = 'SET_NEWS_SCROLL';
/**
 * Filters
 */
export const SET_FILTER_OPTIONS_CINEMA = 'SET_FILTER_OPTIONS_CINEMA';
export const SET_FILTER_OPTIONS_DAY = 'SET_FILTER_OPTIONS_DAY';
export const SET_FILTER_OPTIONS_TIME = 'SET_FILTER_OPTIONS_TIME';
export const SET_FILTER_OPTIONS_FORMAT = 'SET_FILTER_OPTIONS_FORMAT';
export const SET_FILTER_OPTIONS_OTHER = 'SET_FILTER_OPTIONS_OTHER';
export const RESET_FILTER_OPTIONS_FORMAT = 'RESET_FILTER_OPTIONS_FORMAT';
export const RESET_FILTER_OPTIONS_OTHER = 'RESET_FILTER_OPTIONS_OTHER';
export const SET_AFISHA_ACTIVE_TAB = 'SET_AFISHA_ACTIVE_TAB';
export const SET_FILTER_OPTIONS_MONTH = 'SET_FILTER_OPTIONS_MONTH';
export const SET_FILTER_OPTIONS_CATEGORY = 'SET_FILTER_OPTIONS_CATEGORY';
export const SET_FILTER_OPTIONS_HAVE_SHOW = 'SET_FILTER_OPTIONS_HAVE_SHOW';
export const SET_TAB_FOR_FILTERS = 'SET_TAB_FOR_FILTERS';
/**
 * User
 */
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const USER_EXIT = 'USER_EXIT';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
/**
 * Basket
 */
export const ADD_NEW_CHECK = 'ADD_NEW_CHECK';
export const SET_CHECK_INFO = 'SET_CHECK_INFO'
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const DELETE_CREDIT_CARD = 'DELETE_CREDIT_CARD';
export const SET_BASKET_CARD = 'SET_BASKET_CARD';
/**
 * Loading
 */
export const PROFILE_UPDATE_LOADING = 'PROFILE_UPDATE_LOADING';
export const PROFILE_UPDATE_EMAIL_LOADING = 'PROFILE_UPDATE_EMAIL_LOADING';
export const PROFILE_UPDATE_SUBSCRIPTION_LOADING = 'PROFILE_UPDATE_SUBSCRIPTION_LOADING';
export const PROFILE_UPDATE_PASSWORD_LOADING = 'PROFILE_UPDATE_PASSWORD_LOADING';
/**
 * Timer
 */
export const SET_TIMER = 'SET_TIMER';
export const CLEAR_TIMER = 'CLEAR_TIMER';
export const DEFAULT_TIME = 300;
/**
 * Payment
 */
export const PAYMENT_SET_DATA = 'PAYMENT_SET_DATA';
export const PAYMENT_SET_REDIRECT = 'PAYMENT_SET_REDIRECT';
export const PAYMENT_SET_TYPE = 'PAYMENT_SET_TYPE';
export const PAYMENT_SET_SAVE_CARD = 'PAYMENT_SET_SAVE_CARD';
export const PAYMENT_CLEAR = 'PAYMENT_CLEAR';
/**
 * Payment Fail
 */
export const PAYMENT_FAIL = 'PAYMENT_FAIL';
/**
 * header
 */
export const SET_HEADER_OPEN = 'SET_HEADER_OPEN';
/**
 * Landing
 */
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
/**
 *API STATUS
 */
export const API_STATE = 'API_STATE';
