import React from 'react';

import RccStartTable from '../providers/RCCTableProvider/rccStartTable';
import RccClubTable from '../providers/RCCTableProvider/rccClubTable';

const startColumns = JSON.parse('[[{"style":null,"background":null,"children":{"image":{"style":null,"background":null,"source":"https://silverscreen.by/upload/medialibrary/red/Sman2.png"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Любитель"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"20"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"-5%"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"-5%"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"+"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"-"}}}],[{"style":null,"background":null,"children":{"image":{"style":null,"background":null,"source":"https://silverscreen.by/upload/medialibrary/red/Sman3.png"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Киноман"}}},{"style":null,"background":null,"children":{"label":{"style":4,"background":null,"value":"40"}}},{"style":null,"background":null,"children":{"label":{"style":4,"background":null,"value":"-10%"}}},{"style":null,"background":null,"children":{"label":{"style":4,"background":null,"value":"-10%"}}},{"style":null,"background":null,"children":{"label":{"style":4,"background":null,"value":"+"}}},{"style":null,"background":null,"children":{"label":{"style":4,"background":null,"value":"-"}}}],[{"style":null,"background":null,"children":{"image":{"style":null,"background":null,"source":"https://silverscreen.by/upload/medialibrary/red/Sman4.png"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Эксперт"}}},{"style":null,"background":null,"children":{"label":{"style":3,"background":null,"value":"60"}}},{"style":null,"background":null,"children":{"label":{"style":3,"background":null,"value":"-15%"}}},{"style":null,"background":null,"children":{"label":{"style":3,"background":null,"value":"-15%"}}},{"style":null,"background":null,"children":{"label":{"style":3,"background":null,"value":"+"}}},{"style":null,"background":null,"children":{"label":{"style":3,"background":null,"value":"+"}}}]]');
const startDescription = JSON.parse('[[{"style":null,"background":null,"children":{}},{"style":null,"background":null,"children":{}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"1.Количество билетов, приобретенных в течение предшествующих 365 дней"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"2.Скидка на билеты*"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"3.Скидка на попкорн и напитки**"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"4.Особые акции и предложения *** только для Владельцев карточек"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"5.Подарок на День рождения от Silver Screen — бесплатное посещение кинотеатра двум персонам****"}}}]]');
const clubColumns = JSON.parse('[[{"style":null,"background":null,"children":{"image":{"style":null,"background":null,"source":"https://silverscreen.by/upload/medialibrary/red/Sman1.2.png"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Новичок"},"label1":{"style":null,"background":null,"value":"0 уровень"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"0"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"0%"}}}],[{"style":null,"background":null,"children":{"image":{"style":null,"background":null,"source":"https://silverscreen.by/upload/medialibrary/red/Sman2.2.png"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Любитель"},"label1":{"style":null,"background":null,"value":"I уровень"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"20"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"-5%"}}}],[{"style":null,"background":null,"children":{"image":{"style":null,"background":null,"source":"https://silverscreen.by/upload/medialibrary/red/Sman3.2.png"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Киноман"},"label1":{"style":null,"background":null,"value":"II уровень"}}},{"style":null,"background":null,"children":{"label":{"style":4,"background":null,"value":"40"}}},{"style":null,"background":null,"children":{"label":{"style":4,"background":null,"value":"-10%"}}}],[{"style":null,"background":null,"children":{"image":{"style":null,"background":null,"source":"https://silverscreen.by/upload/medialibrary/red/Sman4.2.png"}}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Эксперт"},"label1":{"style":null,"background":null,"value":"III уровень"}}},{"style":null,"background":null,"children":{"label":{"style":3,"background":null,"value":"60"}}},{"style":null,"background":null,"children":{"label":{"style":3,"background":null,"value":"-15%"}}}]]');
const clubDescription = JSON.parse('[[{"style":null,"background":null,"children":{}},{"style":null,"background":null,"children":{"label":{"style":5,"background":null,"value":"Уровни участия в Программе лояльности"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"1.Количество билетов, приобретенных в течение предшествующих 365 дней"}}},{"style":null,"background":null,"children":{"label":{"style":null,"background":null,"value":"2.Размер скидки"}}}]]');

const StartTable = () => (
  <React.Fragment>
    <div style={{ height: '300px' }} />
    <RccStartTable columns={startColumns} description={startDescription} />
  </React.Fragment>
);

const ClubTable = () => (
  <React.Fragment>
    <RccClubTable columns={clubColumns} description={clubDescription} />
  </React.Fragment>
);

export {
  StartTable,
  ClubTable,
};
